// Sample novel data — Spanish literary fiction
const BOOK = {
  title: "El jardín de las horas quietas",
  author: "Marina Cifuentes",
  subtitle: "una novela",
  publisher: "Ediciones Libria",
  year: 2026,
  isbn: "978-84-19283-47-2",
};

const CHAPTERS = [
  {
    id: "front-half",
    kind: "front",
    label: "Media portada",
    title: "El jardín de las horas quietas",
    words: 3,
    body: [
      { type: "halftitle", text: "El jardín de las horas quietas" },
    ],
  },
  {
    id: "front-title",
    kind: "front",
    label: "Portada",
    title: "Portada",
    words: 12,
    body: [
      { type: "title", text: "El jardín de las horas quietas" },
      { type: "subtitle", text: "una novela" },
      { type: "author", text: "Marina Cifuentes" },
      { type: "publisher", text: "Ediciones Libria" },
    ],
  },
  {
    id: "front-copyright",
    kind: "front",
    label: "Página de derechos",
    title: "Derechos de autor",
    words: 84,
    body: [
      { type: "p", text: "Copyright © 2026 Marina Cifuentes" },
      { type: "p", text: "Todos los derechos reservados. Ninguna parte de esta publicación puede ser reproducida, almacenada o transmitida en manera alguna ni por ningún medio, ya sea electrónico, mecánico, químico o de fotocopia, sin permiso previo por escrito de la editorial." },
      { type: "p", text: "Primera edición: marzo de 2026" },
      { type: "p", text: "ISBN 978-84-19283-47-2" },
      { type: "p", text: "Impreso en España" },
    ],
  },
  {
    id: "front-dedication",
    kind: "front",
    label: "Dedicatoria",
    title: "Dedicatoria",
    words: 14,
    body: [
      { type: "dedication", text: "Para mi madre,\nque me enseñó a escuchar\nel sonido de los relojes\ncuando ya no marcan hora." },
    ],
  },
  {
    id: "ch-1",
    kind: "chapter",
    number: 1,
    label: "Capítulo uno",
    title: "La casa de la calle Almendros",
    words: 2847,
    readMin: 11,
    body: [
      { type: "chapter-num", text: "Uno" },
      { type: "chapter-title", text: "La casa de la calle Almendros" },
      { type: "first-p", drop: "L", text: "a casa de la calle Almendros llevaba cuarenta años esperándome, aunque yo no lo supiera. Aquella tarde de septiembre, cuando el taxi me dejó frente a la verja oxidada, sentí por primera vez ese desajuste extraño entre lo que uno cree haber elegido y lo que en realidad lo ha estado eligiendo a uno." },
      { type: "p", text: "Llovía con esa lentitud particular de las lluvias del norte, una lluvia que más que caer parecía instalarse en el aire. El jardín se había vuelto selva: los almendros, que daban nombre a la calle, habían crecido sin podar y sus ramas se entrelazaban formando una bóveda baja y susurrante. Olía a hierba mojada, a hojas en descomposición, a algo más antiguo que no supe nombrar entonces." },
      { type: "p", text: "La llave —una llave de hierro forjado, pesada como un secreto— me la había enviado el notario tres semanas antes, dentro de un sobre acolchado y con una carta breve que repetía dos veces la palabra «condiciones». Las condiciones de mi tía Elvira, fallecida sin testigos en aquella misma casa, eran simples y absurdas: vivir allí seis meses. Ni un día menos. Después, podría venderla, quemarla, regalarla. Lo que quisiera." },
      { type: "scene-break" },
      { type: "p", text: "El recibidor olía a cera fría. Había un perchero de roble con tres abrigos colgados, como si sus dueños fueran a regresar de un momento a otro, y un paragüero de porcelana azul con dos paraguas: uno negro de hombre, otro de seda estampada con cerezos." },
      { type: "p", text: "Dejé la maleta en el suelo y avancé despacio, escuchando la madera del entarimado, que crujía con la familiaridad de quien reconoce a los suyos. En la pared del fondo, un reloj de péndulo marcaba las cuatro y diecisiete. Me acerqué. El péndulo estaba inmóvil." },
      { type: "p", text: "Y sin embargo, el reloj había dado la hora. Estaba segura. Lo había oído desde el porche." },
    ],
  },
  {
    id: "ch-2",
    kind: "chapter",
    number: 2,
    label: "Capítulo dos",
    title: "Los relojes de Elvira",
    words: 3120,
    readMin: 12,
    body: [
      { type: "chapter-num", text: "Dos" },
      { type: "chapter-title", text: "Los relojes de Elvira" },
      { type: "first-p", drop: "C", text: "onté trece relojes en la primera mañana. Estaban en cada habitación: relojes de pared, de sobremesa, uno de cuco con el pájaro arrancado, dos de bolsillo dentro de una vitrina, y un despertador de los años cincuenta sobre la mesilla de mi tía. Ninguno funcionaba. Todos marcaban una hora distinta." },
      { type: "p", text: "El de la cocina, las once y dos. El del salón, las cuatro y diecisiete —el mismo del recibidor—. El del dormitorio principal marcaba las seis y media. Anoté las horas en la libreta nueva que había comprado en la estación, sin saber muy bien por qué lo hacía." },
      { type: "p", text: "Esa noche soñé con mi tía. Estaba sentada en el porche, dándome la espalda, y le daba cuerda a un reloj que no veía. «Las horas no son del tiempo», me decía sin volverse. «Las horas son de quien las espera.»" },
      { type: "scene-break" },
      { type: "p", text: "Por la mañana abrí el cajón superior de la cómoda y encontré la primera carta." },
    ],
  },
  {
    id: "ch-3",
    kind: "chapter",
    number: 3,
    label: "Capítulo tres",
    title: "Cartas que nadie envió",
    words: 2654,
    readMin: 10,
    body: [
      { type: "chapter-num", text: "Tres" },
      { type: "chapter-title", text: "Cartas que nadie envió" },
      { type: "first-p", drop: "E", text: "ran ciento cuarenta y siete cartas. Estaban atadas con una cinta de lino crudo, ordenadas por fecha, y todas tenían el mismo destinatario: «A quien lea esto cuando yo ya no esté». La letra de mi tía, menuda y obstinada, se inclinaba hacia la derecha como si las palabras tuvieran prisa por marcharse de la página." },
      { type: "p", text: "La primera carta estaba fechada el 3 de marzo de 1984. Yo tenía cuatro años." },
      { type: "p", text: "La leí sentada en el suelo, con la espalda contra la cómoda, y al terminar tuve que leerla otra vez, porque la primera lectura no me había dejado entender nada y la segunda tampoco." },
    ],
  },
  {
    id: "ch-4",
    kind: "chapter",
    number: 4,
    label: "Capítulo cuatro",
    title: "El hombre del paraguas negro",
    words: 2912,
    readMin: 11,
    body: [
      { type: "chapter-num", text: "Cuatro" },
      { type: "chapter-title", text: "El hombre del paraguas negro" },
      { type: "first-p", drop: "L", text: "lamó a la puerta el séptimo día. Llovía otra vez —en aquel pueblo siempre llovía—, y al abrir lo primero que vi fue el paraguas: negro, grande, con el mango de madera oscura curvado en cabeza de pato. El mismo paraguas que estaba en el paragüero del recibidor." },
      { type: "p", text: "—Buenos días —dijo—. ¿Es usted la sobrina?" },
      { type: "p", text: "Dije que sí, aunque la palabra me resultó extraña en la boca. Sobrina. Como si hubiera sido sobrina de alguien alguna vez, en activo, y no solo en los registros." },
    ],
  },
  {
    id: "ch-5",
    kind: "chapter",
    number: 5,
    label: "Capítulo cinco",
    title: "Septiembre, otra vez",
    words: 2433,
    readMin: 9,
    body: [
      { type: "chapter-num", text: "Cinco" },
      { type: "chapter-title", text: "Septiembre, otra vez" },
      { type: "first-p", drop: "P", text: "asaron las semanas como pasan las hojas en otoño: sin que uno las cuente. Aprendí a moverme por la casa con los ojos cerrados, a saber qué tabla del entarimado iba a crujir y cuál guardaría silencio, a distinguir el olor del jazmín del patio del olor del jazmín que entraba por la ventana del baño." },
      { type: "p", text: "Una tarde, sin pensarlo, le di cuerda al reloj del recibidor." },
      { type: "p", text: "El péndulo empezó a moverse." },
    ],
  },
  {
    id: "ch-6",
    kind: "chapter",
    number: 6,
    label: "Capítulo seis",
    title: "Lo que devuelve el mar",
    words: 1987,
    readMin: 8,
    status: "draft",
    body: [
      { type: "chapter-num", text: "Seis" },
      { type: "chapter-title", text: "Lo que devuelve el mar" },
      { type: "first-p", drop: "F", text: "uimos hasta la playa el último domingo de octubre. El mar estaba quieto, casi obediente, y devolvía cosas a la arena con una paciencia de viejo: un zapato sin pareja, una botella verde, un trozo de madera pintada que pudo ser parte de un barco o de una puerta." },
    ],
  },
  {
    id: "ch-7",
    kind: "chapter",
    number: 7,
    label: "Capítulo siete",
    title: "El último reloj",
    words: 412,
    readMin: 2,
    status: "outline",
    body: [
      { type: "chapter-num", text: "Siete" },
      { type: "chapter-title", text: "El último reloj" },
      { type: "p", text: "[Esbozo: descubrir el decimocuarto reloj en el sótano. La carta final. Decidir quedarse.]" },
    ],
  },
  {
    id: "back-acks",
    kind: "back",
    label: "Agradecimientos",
    title: "Agradecimientos",
    words: 142,
    body: [
      { type: "h1", text: "Agradecimientos" },
      { type: "p", text: "A J., que leyó cada borrador con la paciencia de quien sabe esperar a que las palabras encuentren su sitio." },
      { type: "p", text: "A mi editora, Lucía Ferré, por las preguntas precisas y los silencios oportunos." },
      { type: "p", text: "Y a la casa de la calle Almendros, que existe, aunque no en el mapa." },
    ],
  },
  {
    id: "back-author",
    kind: "back",
    label: "Sobre la autora",
    title: "Sobre la autora",
    words: 98,
    body: [
      { type: "h1", text: "Sobre la autora" },
      { type: "p", text: "Marina Cifuentes (Oviedo, 1981) es autora de las novelas Las islas que no fueron (2018) y El cuaderno de horas (2022), ambas finalistas del Premio Herralde. Su obra ha sido traducida a once idiomas. Vive entre Asturias y Lisboa." },
    ],
  },
];

window.BOOK = BOOK;
window.CHAPTERS = CHAPTERS;
